name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_HUB_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWD }}
    - name: Build all the images and push it
      run: for dir in */; do [ -d "$dir" ] && [ -f "$dir/build.sh" ] && echo "Executing build.sh in $dir" && (cd "$dir" && bash build.sh) || echo "No build.sh found in $dir"; done
    
    
    
